# Generated by Django 2.2 on 2020-08-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter Product Name', max_length=10)),
                ('description', models.TextField(help_text='Type Description')),
                ('price', models.FloatField(help_text='Price Of Product')),
            ],
        ),
    ]
