# Generated by Django 2.2 on 2020-08-04 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
