# Generated by Django 2.2 on 2020-08-04 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_product_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetails',
            options={'ordering': ['phone']},
        ),
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_allocating', to='App.Batch'),
        ),
        migrations.AlterModelTable(
            name='userdetails',
            table='UserDetails',
        ),
    ]
