# Generated by Django 2.2 on 2020-08-04 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20200804_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_More',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Person_More',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('invite_reason', models.CharField(max_length=64)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Group_More')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Person_More')),
            ],
        ),
        migrations.AddField(
            model_name='group_more',
            name='members',
            field=models.ManyToManyField(through='App.Membership', to='App.Person_More'),
        ),
    ]
