# Generated by Django 2.2 on 2020-08-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20200804_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='courses',
            field=models.ManyToManyField(to='App.Course'),
        ),
    ]
