# Generated by Django 2.1.4 on 2018-12-20 13:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_dmo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
