# Generated by Django 4.1.1 on 2022-09-18 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0002_securefiles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SecureFiles',
        ),
    ]
