# Generated by Django 4.1.1 on 2022-09-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0003_delete_securefiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecureFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo1', models.ImageField(upload_to='secure')),
                ('photo2', models.ImageField(upload_to='open')),
            ],
        ),
    ]
