# Generated by Django 4.1.1 on 2022-09-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0007_batch_course_group_more_person_more_userdetails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter Product Name', max_length=10)),
                ('description', models.TextField(help_text='Type Description')),
                ('price', models.FloatField(help_text='Price Of Product')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
