# Generated by Django 4.1.1 on 2022-09-21 18:43

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0008_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            managers=[
                ('book_filter_by_tagor', django.db.models.manager.Manager()),
            ],
        ),
    ]
