# Generated by Django 2.2 on 2020-01-15 21:46

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogId', models.TextField()),
                ('blogHeading', models.TextField()),
                ('blogContent', models.TextField()),
                ('blogImage', models.ImageField(upload_to='BlogImage/')),
                ('blogCreatorName', models.TextField()),
                ('blogCreatorMail', models.EmailField(max_length=254)),
                ('blogCreatorImage', models.ImageField(upload_to='BlogerImage/')),
                ('blogLikedBy', djongo.models.fields.ListField(default=[])),
                ('blogDisLikeBy', djongo.models.fields.ListField(default=[])),
                ('blogComment', djongo.models.fields.ListField(default={})),
                ('blogLikeCount', models.IntegerField()),
                ('blogDisLikeCount', models.IntegerField()),
                ('blogPostTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usrId', models.TextField()),
                ('usrName', models.TextField()),
                ('usrFirstName', models.TextField()),
                ('usrLastName', models.TextField()),
                ('usrMail', models.EmailField(max_length=254)),
                ('usrImage', models.ImageField(upload_to='')),
                ('usrPassword', models.TextField()),
                ('usrCreated', models.TimeField()),
            ],
        ),
    ]
